services:
  nginx01:
    container_name: nginx01
    image: docker.io/nginx:latest
    tty: true
    volumes:
      - ./nginx_conf/html/nginx01.html:/usr/share/nginx/html/index.html:ro
      - ./nginx_conf/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      nginx_haproxy_seg:
        ipv4_address: 172.25.10.10
  nginx02:
    container_name: nginx02
    image: docker.io/nginx:latest
    tty: true
    volumes:
      - ./nginx_conf/html/nginx02.html:/usr/share/nginx/html/index.html:ro
      - ./nginx_conf/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      nginx_haproxy_seg:
        ipv4_address: 172.25.10.11
  haproxy:
    container_name: haproxy
    image: docker.io/haproxy:latest
    tty: true
    volumes:
      - ./haproxy_conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      nginx_haproxy_seg:
        ipv4_address: 172.25.10.20
  curl:
    container_name: curl
    image: docker.io/curlimages/curl:latest
    command: sh
    tty: true
    networks:
      nginx_haproxy_seg:
        ipv4_address: 172.25.10.30
networks:
  nginx_haproxy_seg:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.25.10.0/24"
        gateway: "172.25.10.1"